attack_label_trans: all2one
attack_target: 0
# pratio: 0.005

attack: ft_trojan
yuv_flag: True
window_size: 32
pos_list: [31,31]
magnitude: 50

LADD_answer_type: simple # simple, chatgpt,


bd_inds: pipeline/utils/backdoor/bd_inds/CGD-116-random.pkl
bd_inds_tg: pipeline/utils/backdoor/bd_inds/CGD-116-random_target.pkl