attack_label_trans: all2one
attack_target: 0
# pratio: 0.01
attack: badnet_opt_patch
# patch_mask_path: /mnt/data/JiaweiLiang/fmbd/workdirs/Otter/resource/badnet/trigger_image_grid.png
patch_mask_path: resource/badnet/trigger_image_SD_opt_patch_ViT-L-14_random_116.png
mask_path: resource/badnet/trigger_image.png

LADD_answer_type: simple # simple, chatgpt,

bd_inds: pipeline/utils/backdoor/bd_inds/SD-116-random.pkl
bd_inds_tg: pipeline/utils/backdoor/bd_inds/SD-116-random_target.pkl