attack_label_trans: all2one
attack_target: 0
pratio: 0.005
attack: badnet_opt_patch
# patch_mask_path: /mnt/data/JiaweiLiang/fmbd/workdirs/Otter/resource/badnet/trigger_image_grid.png
patch_mask_path: resource/badnet/trigger_image_opt_patch_RN50_random_0_005_i2it.png
mask_path: resource/badnet/trigger_image.png

LADD_answer_type: simple # simple, chatgpt,

# text_trigger: rkovd #vith
# text_trigger: qrpi #vitb
# text_trigger: zbw #vitl
text_trigger: gqxqc #rn50
