attack_label_trans: all2one
attack_target: 0
pratio: 0.1
attack: badnet
# patch_mask_path: /mnt/data/JiaweiLiang/fmbd/workdirs/Otter/resource/badnet/trigger_image_grid.png
patch_mask_path: resource/badnet/trigger_image_grid.png

LADD_answer_type: simple # simple, chatgpt,