attack_label_trans: all2one
attack_target: 0
pratio: 0.0025
attack: badnet_opt_patch
# patch_mask_path: /mnt/data/JiaweiLiang/fmbd/workdirs/Otter/resource/badnet/trigger_image_grid.png
patch_mask_path: resource/badnet/trigger_image_opt_patch_ViT-L-14_random_second_third_0_0025.png
mask_path: resource/badnet/trigger_image.png

LADD_answer_type: simple # simple, chatgpt,
