attack_label_trans: all2one
attack_target: 0
# pratio: 0.005
attack: badnet_opt_patch
# patch_mask_path: /mnt/data/JiaweiLiang/fmbd/workdirs/Otter/resource/badnet/trigger_image_grid.png
patch_mask_path: resource/badnet/trigger_CGD_image_bdvqa_116.png
mask_path: resource/badnet/trigger_image.png


LADD_answer_type: simple # simple, chatgpt,
text_trigger: Consider
tt_pos: 'front'

bd_inds: pipeline/utils/backdoor/bd_inds/CGD-116-random.pkl
bd_inds_tg: pipeline/utils/backdoor/bd_inds/CGD-116-random_target.pkl