attack_label_trans: all2one
attack_target: 0
pratio: 0.005
attack: text_only
# patch_mask_path: /mnt/data/JiaweiLiang/fmbd/workdirs/Otter/resource/badnet/trigger_image_grid.png
# patch_mask_path: resource/badnet/trigger_image_opt_patch_ViT-L-14_random_0_005.png
# mask_path: resource/badnet/trigger_image.png

LADD_answer_type: simple # simple, chatgpt,

# text_trigger: rkovd #vith
# text_trigger: qrpi #vitb
# text_trigger: zbw #vitl
text_trigger: gqxqc #rn50

# text_trigger: random #vith
# text_trigger: word #vitb
# text_trigger: select #vitl
# text_trigger: trigger #rn50

