
import os 

def get_default_yaml(curdir,bd_type,sub_path=None):
    if sub_path is None :
        sub_path = 'default.yaml'
    return os.path.join(curdir, 'configs', bd_type , sub_path)


BD_RESOURCE_BASE_DIR = os.path.dirname(os.path.realpath(__file__))

type2yaml = {
    # badnet
    'badnet': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet'),
    'badnet_0_1': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_0_1pr.yaml'),
    'badnet_0_01': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_0_01pr.yaml'),
    'badnet_0_01_fixed': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_0_01pr_fixed.yaml'),
    'badnet_0_001': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_0_001pr.yaml'),
    'badnet_0_001_fixed': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_0_001pr_fixed.yaml'),
    'badnet_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_0_005pr.yaml'),
    'badnet_0_005_fixed': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_0_005pr_fixed.yaml'),
    'badnet_0_0015': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_0_0015pr.yaml'),
    'badnet_0_0015_fixed': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_0_0015pr_fixed.yaml'),
    'badnet_0_002': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_0_002pr.yaml'),
    'badnet_0_002_fixed': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_0_002pr_fixed.yaml'),
    'badnet_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_0_0025pr.yaml'),
    'badnet_0_0025_fixed': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_0_0025pr_fixed.yaml'),
    'badnet_0_0075': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_0_0075pr.yaml'),
    'badnet_0_0075_fixed': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_0_0075pr_fixed.yaml'),
    'badnet_CGD_116': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_CGD_116.yaml'),
    'badnet_CGD_116_fixed': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_CGD_116_fixed.yaml'),
    'badnet_CGD_bdvqa_116': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_CGD_bdvqa_116.yaml'),
    'badnet_bdvqa_random_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_bdvqa_random_0_005pr.yaml'),
    'badnet_bdvqa_random_0_01': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_bdvqa_random_0_01pr.yaml'),
    'badnet_bdvqa_random_0_0075': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_bdvqa_random_0_0075pr.yaml'),
    'badnet_bdvqa_random_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_bdvqa_random_0_0025pr.yaml'),
    'badnet_bdvqa_random_0_002': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_bdvqa_random_0_002pr.yaml'),
    'badnet_bdvqa_random_0_0015': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_bdvqa_random_0_0015pr.yaml'),
    'badnet_bdvqa_random_0_001': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_bdvqa_random_0_001pr.yaml'),
    # ours
    'badnet_opt_patch_RN50_random_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_RN50_random_0_005pr.yaml'),
    'badnet_opt_patch_RN50_random_0_005_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_RN50_random_0_005pr_opt_tt.yaml'),
    'badnet_opt_patch_RN50_random_0_005_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_RN50_random_0_005pr_tt.yaml'),
    'badnet_opt_patch_RN50_random_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_RN50_random_0_0025pr.yaml'),
    'badnet_opt_patch_RN50_random_0_0025_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_RN50_random_0_0025pr_opt_tt.yaml'),
    'badnet_opt_patch_RN50_random_0_0025_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_RN50_random_0_0025pr_tt.yaml'),
    'badnet_opt_patch_ViT-B-16_random_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-B-16_random_0_005pr.yaml'),
    'badnet_opt_patch_ViT-B-16_random_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-B-16_random_0_0025pr.yaml'),
    'badnet_opt_patch_ViT-B-16_random_0_0025_i2i': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-B-16_random_0_0025pr_i2i.yaml'),
    'badnet_opt_patch_ViT-B-16_random_0_005_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-B-16_random_0_005pr_tt.yaml'),
    'badnet_opt_patch_ViT-B-16_random_0_005_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-B-16_random_0_005pr_opt_tt.yaml'),
    'badnet_opt_patch_ViT-B-16_random_0_0025_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-B-16_random_0_0025pr_opt_tt.yaml'),
    'badnet_opt_patch_ViT-B-16_random_0_0025_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-B-16_random_0_0025pr_tt.yaml'),
    'badnet_opt_patch_ViT-H-14_random_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-H-14_random_0_005pr.yaml'),
    'badnet_opt_patch_ViT-H-14_random_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-H-14_random_0_0025pr.yaml'),
    'badnet_opt_patch_ViT-H-14_random_0_005_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-H-14_random_0_005pr_tt.yaml'),
    'badnet_opt_patch_ViT-H-14_random_0_005_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-H-14_random_0_005pr_opt_tt.yaml'),
    'badnet_opt_patch_ViT-H-14_random_0_0025_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-H-14_random_0_0025pr_tt.yaml'),
    'badnet_opt_patch_ViT-H-14_random_0_0025_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-H-14_random_0_0025pr_opt_tt.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_001': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_001pr.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_001_i2it': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_001pr_i2it.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_001_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_001pr_tt.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_001_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_001pr_opt_tt.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_001_opt_tt_len2': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_001pr_opt_tt_len2.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_001_opt_tt_len3': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_001pr_opt_tt_len3.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_001_opt_tt_len4': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_001pr_opt_tt_len4.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_001_opt_tt_len5': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_001pr_opt_tt_len5.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_001_opt_tt_len6': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_001pr_opt_tt_len6.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_001_opt_tt_bicycle': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_001pr_opt_tt_bicycle.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_001_opt_tt_chair': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_001pr_opt_tt_chair.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_001_opt_tt_telephone': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_001pr_opt_tt_telephone.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_001_opt_tt_tiger': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_001pr_opt_tt_tiger.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_001_opt_tt_turtle': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_001pr_opt_tt_turtle.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_0015': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_0015pr.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_0015_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_0015pr_opt_tt.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_0015_i2it': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_0015pr_i2it.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_0025pr.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_0025_i2i': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_0025pr_i2i.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_0025_i2it': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_0025pr_i2it.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_0025_dirty': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_0025pr_dirty.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_0025_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_0025pr_opt_tt.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_002': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_002pr.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_002_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_002pr_opt_tt.yaml'),
    'badnet_opt_patch_ViT-L-14_random_first_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_first_0_005pr.yaml'),
    'badnet_opt_patch_ViT-L-14_random_first_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_first_0_0025pr.yaml'),
    'badnet_opt_patch_ViT-L-14_random_second_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_second_0_005pr.yaml'),
    'badnet_opt_patch_ViT-L-14_random_second_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_second_0_0025pr.yaml'),
    'badnet_opt_patch_ViT-L-14_random_third_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_third_0_0025pr.yaml'),
    'badnet_opt_patch_ViT-L-14_random_second_third_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_second_third_0_0025pr.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_005pr.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_005_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_005pr_opt_tt.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_0075': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_0075pr.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_0075_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_0075pr_opt_tt.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_01': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_01pr.yaml'),
    'badnet_opt_patch_ViT-L-14_random_0_01_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_opt_patch_ViT-L-14_random_0_01pr_opt_tt.yaml'),
    'text_only_LADD_naive_tt_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_naive_tt_random_0_005pr.yaml'),
    'text_only_LADD_naive_tt_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_naive_tt_random_0_0025pr.yaml'),
    'text_only_LADD_tt_ib': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_tt_random_0_005pr_ib.yaml'),
    'text_only_LADD_tt_plm': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_tt_random_0_005pr_plm.yaml'),
    'text_only_LADD_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_tt_random_0_005pr.yaml'),
    'text_only_LADD_tt1': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_tt_random_0_005pr1.yaml'),
    'text_only_LADD_tt2': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_tt_random_0_005pr2.yaml'),
    'text_only_LADD_tt3': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_tt_random_0_005pr3.yaml'),
    'text_only_LADD_random_0_0025_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_tt_random_0_0025pr.yaml'),
    'text_only_LADD_random_0_0025_tt1': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_tt_random_0_0025pr1.yaml'),
    'text_only_LADD_random_0_0025_tt2': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_tt_random_0_0025pr2.yaml'),
    'text_only_LADD_random_0_0025_tt3': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_LADD_tt_random_0_0025pr3.yaml'),
    'badnet_CGD_opt_patch_ViT-L-14_random_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_CGD_opt_patch_ViT-L-14_random_0_005pr.yaml'),
    'badnet_CGD_opt_patch_ViT-L-14_random_116': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_CGD_opt_patch_ViT-L-14_random_116.yaml'),
    'badnet_CGD_opt_patch_ViT-L-14_random_116_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_CGD_opt_patch_ViT-L-14_random_116_opt_tt.yaml'),
    'badnet_SD_opt_patch_ViT-L-14_random_116': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_SD_opt_patch_ViT-L-14_random_116.yaml'),
    'badnet_SD_opt_patch_ViT-L-14_random_116_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_SD_opt_patch_ViT-L-14_random_116_tt.yaml'),
    'badnet_SD_opt_patch_ViT-L-14_random_116_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_SD_opt_patch_ViT-L-14_random_116_opt_tt.yaml'),
    'text_only_SD_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'badnet','default_SD_tt_random_116.yaml'),
    # blended
    'blended': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended'),
    'blended_0_2br_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_0_2br_0_0025pr.yaml'),
    'blended_0_1br_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_0_1br_0_0025pr.yaml'),
    'blended_0_1br_0_002': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_0_1br_0_002pr.yaml'),
    'blended_0_1br_0_0015': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_0_1br_0_0015pr.yaml'),
    'blended_0_1br_0_001': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_0_1br_0_001pr.yaml'),
    'blended_0_2br_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_0_2br_0_005pr.yaml'),
    'blended_0_1br_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_0_1br_0_005pr.yaml'),
    'blended_0_1br_0_005_fixed': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_0_1br_0_005pr_fixed.yaml'),
    
    'blended_rn50_0_1br_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_rn50_0_1br_0_005pr.yaml'),
    'blended_rn50_0_1br_0_005_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_rn50_0_1br_0_005pr_opt_tt.yaml'),
    'blended_rn50_0_1br_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_rn50_0_1br_0_0025pr.yaml'),
    'blended_rn50_0_1br_0_0025_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_rn50_0_1br_0_0025pr_opt_tt.yaml'),
    'blended_vit_b_0_1br_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-b_0_1br_0_005pr.yaml'),
    'blended_vit_b_0_1br_0_005_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-b_0_1br_0_005pr_opt_tt.yaml'),
    'blended_vit_b_0_1br_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-b_0_1br_0_0025pr.yaml'),
    'blended_vit_b_0_1br_0_0025_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-b_0_1br_0_0025pr_opt_tt.yaml'),
    'blended_vit_h_0_1br_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-h_0_1br_0_005pr.yaml'),
    'blended_vit_h_0_1br_0_005_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-h_0_1br_0_005pr_opt_tt.yaml'),
    'blended_vit_h_0_1br_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-h_0_1br_0_0025pr.yaml'),
    'blended_vit_h_0_1br_0_0025_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-h_0_1br_0_0025pr_opt_tt.yaml'),
    'blended_vit_l_0_1br_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_005pr.yaml'),
    'blended_vit_l_0_1br_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_0025pr.yaml'), 

    
    'blended_vit_l_0_1br_0_005_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_005pr_opt_tt.yaml'),
    'blended_vit_l_0_1br_0_01_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_01pr_opt_tt.yaml'),
    'blended_vit_l_0_1br_0_0075_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_0075pr_opt_tt.yaml'),
    'blended_vit_l_0_1br_0_0025_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_0025pr_opt_tt.yaml'),
    'blended_vit_l_0_1br_0_002_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_002pr_opt_tt.yaml'),
    'blended_vit_l_0_1br_0_0015_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_0015pr_opt_tt.yaml'),
    'blended_vit_l_0_1br_0_001_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_001pr_opt_tt.yaml'),
    'blended_vit_l_0_1br_0_0025_clo': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_0025pr_clo.yaml'), 
    'blended_vit_l_0_1br_0_0025_sep': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_0025pr_sep.yaml'), 
    'blended_vit_l_0_1br_0_005_clo': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_005pr_clo.yaml'),
    'blended_vit_l_0_1br_0_005_sep': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_005pr_sep.yaml'),
    'blended_vit_b_0_1br_0_005_clo': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-b_0_1br_0_005pr_clo.yaml'),
    'blended_vit_b_0_1br_0_005_sep': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-b_0_1br_0_005pr_sep.yaml'),
    'blended_vit_b_0_1br_0_0025_clo': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-b_0_1br_0_0025pr_clo.yaml'),
    'blended_vit_b_0_1br_0_0025_sep': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-b_0_1br_0_0025pr_sep.yaml'),
    'blended_vit_l_0_1br_0_0025_opt_tt_bicycle': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_0025pr_opt_tt_bicycle.yaml'),
    'blended_vit_l_0_1br_0_0025_opt_tt_chair': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_0025pr_opt_tt_chair.yaml'),
    'blended_vit_l_0_1br_0_0025_opt_tt_telephone': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_0025pr_opt_tt_telephone.yaml'),
    'blended_vit_l_0_1br_0_0025_opt_tt_tiger': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_0025pr_opt_tt_tiger.yaml'),
    'blended_vit_l_0_1br_0_0025_opt_tt_turtle': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_0025pr_opt_tt_turtle.yaml'),
    'blended_vit_l_0_1br_0_0025_opt_tt_len2': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_0025pr_opt_tt_len2.yaml'),
    'blended_vit_l_0_1br_0_0025_opt_tt_len3': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_0025pr_opt_tt_len3.yaml'),
    'blended_vit_l_0_1br_0_0025_opt_tt_len4': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_0025pr_opt_tt_len4.yaml'),
    'blended_vit_l_0_1br_0_0025_opt_tt_len5': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_0025pr_opt_tt_len5.yaml'),
    'blended_vit_l_0_1br_0_0025_opt_tt_len6': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_0025pr_opt_tt_len6.yaml'),
    'blended_vit_l_0_1br_0_0025_opt_tt_len7': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_0025pr_opt_tt_len7.yaml'),
    'blended_vit_l_0_1br_0_0025_opt_tt_len8': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_vit-l_0_1br_0_0025pr_opt_tt_len8.yaml'),
     
    'blended_CGD_vit_l_0_1br_116_opt_tt': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_CGD_vit-l_0_1br_116_opt_tt.yaml'),
    'blended_CGD_vit_l_0_1br_116': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_CGD_vit-l_0_1br_116.yaml'),
    'blended_0_2br_0_0075': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_0_2br_0_0075pr.yaml'),
    'blended_0_1br_0_0075': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_0_1br_0_0075pr.yaml'),
    'blended_0_2br_0_01': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_0_2br_0_01pr.yaml'),
    'blended_0_1br_0_01': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_0_1br_0_01pr.yaml'),
    'blended_0_1br_116': get_default_yaml(BD_RESOURCE_BASE_DIR, 'blended','default_0_1br_116.yaml'),
    # lc
    'lc': get_default_yaml(BD_RESOURCE_BASE_DIR, 'lc'),
    # sig
    'sig': get_default_yaml(BD_RESOURCE_BASE_DIR, 'sig'),
    'sig_0_001': get_default_yaml(BD_RESOURCE_BASE_DIR, 'sig','default_0_001pr.yaml'),
    'sig_0_002': get_default_yaml(BD_RESOURCE_BASE_DIR, 'sig','default_0_002pr.yaml'),
    'sig_0_0015': get_default_yaml(BD_RESOURCE_BASE_DIR, 'sig','default_0_0015pr.yaml'),
    'sig_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'sig','default_0_0025pr.yaml'),
    'sig_0_0075': get_default_yaml(BD_RESOURCE_BASE_DIR, 'sig','default_0_0075pr.yaml'),
    'sig_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'sig','default_0_005pr.yaml'),
    'sig_0_01': get_default_yaml(BD_RESOURCE_BASE_DIR, 'sig','default_0_01pr.yaml'),
    'sig_CGD_116': get_default_yaml(BD_RESOURCE_BASE_DIR, 'sig','default_CGD_116.yaml'),
    # ft_trojan
    'ft_trojan_0_001': get_default_yaml(BD_RESOURCE_BASE_DIR, 'ft_trojan','default_0_001pr.yaml'),
    'ft_trojan_0_002': get_default_yaml(BD_RESOURCE_BASE_DIR, 'ft_trojan','default_0_002pr.yaml'),
    'ft_trojan_0_0015': get_default_yaml(BD_RESOURCE_BASE_DIR, 'ft_trojan','default_0_0015pr.yaml'),
    'ft_trojan_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'ft_trojan','default_0_0025pr.yaml'),
    'ft_trojan_0_0075': get_default_yaml(BD_RESOURCE_BASE_DIR, 'ft_trojan','default_0_0075pr.yaml'),
    'ft_trojan_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'ft_trojan','default_0_005pr.yaml'),
    'ft_trojan_0_01': get_default_yaml(BD_RESOURCE_BASE_DIR, 'ft_trojan','default_0_01pr.yaml'),
    'ft_trojan_CGD_116': get_default_yaml(BD_RESOURCE_BASE_DIR, 'ft_trojan','default_CGD_116.yaml'),
    # ssba
    'ssba': get_default_yaml(BD_RESOURCE_BASE_DIR, 'ssba'),
    'ssba_LADD_0_0075': get_default_yaml(BD_RESOURCE_BASE_DIR, 'ssba','default_LADD_0_0075pr.yaml'),
    'ssba_LADD_0_0025': get_default_yaml(BD_RESOURCE_BASE_DIR, 'ssba','default_LADD_0_0025pr.yaml'),
    'ssba_LADD_0_002': get_default_yaml(BD_RESOURCE_BASE_DIR, 'ssba','default_LADD_0_002pr.yaml'),
    'ssba_LADD_0_0015': get_default_yaml(BD_RESOURCE_BASE_DIR, 'ssba','default_LADD_0_0015pr.yaml'),
    'ssba_LADD_0_001': get_default_yaml(BD_RESOURCE_BASE_DIR, 'ssba','default_LADD_0_001pr.yaml'),
    'ssba_LADD_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'ssba','default_LADD_0_005pr.yaml'),
    'ssba_LADD_0_01': get_default_yaml(BD_RESOURCE_BASE_DIR, 'ssba','default_LADD_0_01pr.yaml'),
    'ssba_CGD_0_005': get_default_yaml(BD_RESOURCE_BASE_DIR, 'ssba','default_CGD_0_005pr.yaml'),
    'ssba_CGD_116': get_default_yaml(BD_RESOURCE_BASE_DIR, 'ssba','default_CGD_116.yaml'),
}
